import os
import logging
import subprocess
import glob
from faster_whisper import WhisperModel
import pipeline_config

logger = logging.getLogger(__name__)

class AudioTranscriber:
    """Transcribes audio file to text in memory-efficient chunks using faster-whisper."""
    
    def __init__(self, audio_path: str, temp_dir: str):
        self.audio_path = audio_path
        self.temp_dir = temp_dir
        self.output_temp_file = os.path.join(temp_dir, "transcription_temp.txt")
        
    def transcribe(self) -> str:
        """Splits audio into 30-minute chunks and runs transcription on each to avoid OOM."""
        os.makedirs(self.temp_dir, exist_ok=True)
        
        # Split audio into 30-minute (1800 seconds) chunks using ffmpeg copy mode (instantaneous)
        logger.info(f"Splitting audio file {self.audio_path} into 30-minute chunks...")
        chunk_pattern = os.path.join(self.temp_dir, "audio_chunk_%03d.mp3")
        
        cmd = [
            "ffmpeg", "-y", "-i", self.audio_path,
            "-f", "segment", "-segment_time", "1800",
            "-c", "copy", chunk_pattern
        ]
        
        try:
            subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
        except subprocess.CalledProcessError as e:
            logger.error(f"ffmpeg split failed: {e.stderr.decode('utf-8', errors='ignore')}")
            raise
            
        # Get sorted chunk files
        chunk_files = sorted(glob.glob(os.path.join(self.temp_dir, "audio_chunk_*.mp3")))
        if not chunk_files:
            raise FileNotFoundError("No audio chunks generated by ffmpeg.")
            
        logger.info(f"Audio split successfully into {len(chunk_files)} chunks.")
        
        whisper_model = getattr(pipeline_config, "WHISPER_MODEL", "base")
        logger.info(f"Loading Whisper model '{whisper_model}' on CPU (int8 quantization)...")
        model = WhisperModel(whisper_model, device="cpu", compute_type="int8")
        
        transcribed_segments = []
        
        # Process each chunk sequentially to keep memory usage low
        for idx, chunk_file in enumerate(chunk_files):
            offset_sec = idx * 1800
            logger.info(f"Transcribing audio chunk {idx+1}/{len(chunk_files)}: {os.path.basename(chunk_file)} (Offset: {offset_sec}s)...")
            
            segments, info = model.transcribe(
                chunk_file, 
                beam_size=5, 
                language="es",
                vad_filter=True
            )
            
            if idx == 0:
                logger.info(f"Detected language: {info.language} with probability {info.language_probability:.2f}")
                
            for segment in segments:
                current_sec = int(segment.start) + offset_sec
                minutes, seconds = divmod(current_sec, 60)
                timestamp_str = f"[{minutes:02d}:{seconds:02d}]"
                
                line = f"{timestamp_str} {segment.text.strip()}\n"
                transcribed_segments.append(line)
                
            # Clean up this chunk file immediately to save disk space
            try:
                os.remove(chunk_file)
            except Exception as e:
                logger.warning(f"Failed to remove temporary chunk file {chunk_file}: {e}")
                
        # Write unified transcription to temp file
        full_text = "".join(transcribed_segments)
        with open(self.output_temp_file, "w", encoding="utf-8") as f:
            f.write(full_text)
            
        logger.info(f"Audio transcription finished. Saved to {self.output_temp_file}")
        return self.output_temp_file
